id: 'test_ae'
model: AE
beta:
model_params:
  class_latent_size: 16
  content_latent_size: 64
training:
  data_root: './64_frames'
  eval_root: './64_frames_test'
  epoch: 200
  num_workers: 4
  batch_size: 100
  lr: 0.0001
  corruptions: ['gaussianBlur', 'speckleNoise', 'impulseNoise']
  intensities: [1,1,1]
  save_freq: 10