id: 'weather'
model: DARLA
beta: 20
bloss_coeff: 20
model_params:
  class_latent_size: 16
  content_latent_size: 64
  AE_weight_path: './checkpoints/AE/test_ae/best_model.pt'
training:
  data_root: './64_frames'
  eval_root: './64_frames_test'
  epoch: 200
  num_workers: 4
  batch_size: 100
  lr: 0.0001
  corruptions: ['frost', 'fog']
  intensities: [5,5]
  save_freq: 10
eval:
  path: ./checkpoints/DARLA/weather_20/best_model.pt
  root: './64_frames_test'
  corruptions: ['frost', 'fog', 'gaussianBlur', 'speckleNoise', 'impulseNoise']
  intensities: [5,5,1,1,1]