beta: 1
id: weather
model: DDVAE
model_params:
  class_latent_size: 16
  content_latent_size: 64
training:
  batch_size: 100
  corruptions:
  - rain
  - frost
  - fog
  data_root: ./64_frames
  epoch: 200
  eval_root: ./64_frames_test
  intensities:
  - 1
  - 5
  - 5
  lr: 0.0001
  num_workers: 4
  save_freq: 10
